### ISSUE TITLE
Estilo das Widgets do Rodapé

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/Tema-IPHAN-INRC#1]

**Comment by mateuswetah** [comment]
@dvespasiano consegui dar uma testada agr, alguns comentários:

1. Olhando pro documento do rodapé, embora eles não deixem isso muito claro, mas é preciso tratar os casos em que há mais de 4 widgets ou que a tela não tem espaço para as 4 widgets atuais:

https://drive.google.com/drive/folders/13qyhFyRwCy0TVuLSuOdMBL4ZHr8Gy9oZ

Se vc olhar no tamanho médio lá eles esperam que uma linha caia pra baixo da outra, mantendo inclusive uma margem lateral entre elas. Embora eu ache isso meio difícil de se tratar dessa maneira (no caso deles a última widget acabou embaixo da penúltima, ao invés de ir pra baixo da primeira), podemos pensar num esquema de máximo 4 widgets por linha em um tamanho, máximo 3 em outro... e assim ir quebrando em novas linhas este. O que acha?

2. Acho que tem algumas das widgets q ainda mereciam um trato... especialmente a de buscar que tá bem feia:
![image](https://user-images.githubusercontent.com/1184874/100234029-442dde80-2f09-11eb-89ad-37409e76719b.png)

Este link do mês por exemplo que está cinza, eu esperaria branco mesmo aí. A galeria, talvez poderíamos deixar uma margem menor de `1em`, ao invés de `1.5em` e igual tanto nas laterais quanto acima. Enfim, são pitacos, não tenho certeza do melhor caminho mas podemos experimentar.

3. O HR da linha q separa as sessões do rodapé tá com um `border-top` cinzinha, coisa dos css q vieram com o template, vale se livrar dele...

4. Por fim, quando estiver funcionando a questão dos collapses mobile, temos um desafio que é pensar como tratar as widgets sem título!

**Comment by dvespasiano** [comment]
Fiz Algumas alterações e subi tudo já responsivo do Footer
