### ISSUE TITLE
Rodapé Mobile

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/Tema-IPHAN-INRC#2]

**Comment by dvespasiano** [comment]
Completo o rodapé web e mobile tanto em landscape quanto em portrait, tem que fazer apenas um ajuste no expand e collapse, porém tudo já funciona.

**Comment by mateuswetah** [comment]
- [x] Alinhar + do mobile para direita;
- [x] Garantir que ocupe 100% da largura do mobile;
- [x] Padding top de 70px na parte interna do rodapé;
- [x] 70px entre última widget e linha branca;
