### ISSUE TITLE
Template do Inventários

### ISSUE THREAD

**Issue by dvespasiano** [tainacan/Tema-IPHAN-INRC#23]
- [x] Criar template para um `post_type` de item. Para isso você vai criar uma coleção no seu Tainacan, e alguns itens com metadados quaisquer lá. Daí você vai pegar o post type dela (vai ser algo como `tnc_col_1234`. Se tier dúvidas quanto a este processo me avisa. Usando este post type, cria o template customizado pra single dele, baseando-se naquela hierarquia do WP (https://developer.wordpress.org/themes/basics/template-hierarchy/);
- [x] Para mostrar o conteúdo daquela barra lateral cinza, basta usar a função `tainacan_the_metadata()`: https://tainacan.github.io/tainacan-wiki/#/dev/custom-templates?id=create-your-files-for-the-templates
-[ ] O conteúdo do Post em si pode ser Lorem Ipsum, por enquanto. 
- [x] Tratar da responsividade desta barra lateral nova.

**Comment by mateuswetah** [comment]
Por hora vamos abandonar a estratégia do plugin para inserir o conteúdo interno via plugin (https://github.com/tainacan/tainacan/issues/545) embora em breve isto deva virar oficial também (https://github.com/tainacan/tainacan/issues/446). A estratégia feita aqui: 

https://github.com/tainacan/Tema-IPHAN-INRC/commit/318485ea43306e6af88df028ef459aa115974496#diff-363611390fc55f0c584297f55462fc0c71451eedb29932798c22c2143080bb8dR41-R53

já deve bastar.
