### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by vnmedeiros** [tainacan/Tema-IPHAN-INRC#4]
- [x] Mobile
- [x] Desktop

**Comment by dvespasiano** [comment]
Falta só testar com mais ítens no menu, mas ja está funcionando e responsivo, o mobile funcionando para portrait e landscape

**Comment by mateuswetah** [comment]
@dvespasiano acho q vc esqueceu de commitar rsrs. Uma coisa q a gente sugere tbm é sempre referenciar o número da issue quando for escrever o commit, neste caso #4.

**Comment by dvespasiano** [comment]
Subi o posicionamento e vou ir fazendo testes pra ver como fica bom lá dentro

**Comment by mateuswetah** [comment]
Novos (e últimos!) detalhes:

- [ ] Submenus no mobile;
- [ ] Alinhamento burguer menu;
- [ ] Setinha do dropdown de submenu dentro da box do item;
